---
- name: ios | hardware
  ios_facts:
    gather_subset:
      - "hardware"
  register: my_hw_facts
  ignore_errors: true
  tags:
    - "hardware"

- name: ios | interfaces
  ios_facts:
    gather_subset:
      - "interfaces"
  register: my_intf_facts
  ignore_errors: true
  tags:
    - "interfaces"
