---
- name: iosxr | hardware
  iosxr_facts:
    gather_subset:
      - "hardware"
  register: my_hw_facts
  ignore_errors: true
  tags:
    - "hardware"

- name: iosxr | interfaces
  iosxr_facts:
    gather_subset:
      - "interfaces"
  register: my_intf_facts
  ignore_errors: true
  tags:
    - "interfaces"
