---
- name: junos | hardware
  junos_facts:
    gather_subset:
      - "hardware"
  register: my_hw_facts
  ignore_errors: true
  tags:
    - "hardware"

- name: junos | interfaces
  junos_facts:
    gather_subset:
      - "interfaces"
  register: my_intf_facts
  ignore_errors: true
  tags:
    - "interfaces"
